### ISSUE TITLE
[Bug Report] Keep/Release Box dosen't disappear

### ISSUE THREAD

**Issue by Zayne64** [Universal-Team/pkmn-chest#10] opened 2019-06-30 09:53 UTC
**Describe the bug**
When releasing a pokemon, after pressing one of the buttons some of the box stays in the bottom box (the save box)

**To Reproduce**
1. Have a Pokemon
2. Press A
3. Go down to release and Press A
4. Press Keep

**Expected behavior**
Box will disappear

**Screenshots**
Can't get screenshots

**Console (please complete the following information):**
  - [ ] DS/DSi/3DS using a Flashcard
  - [x] DSi (Using SD card)
  - [ ] 3DS (Using SD card)
- Version [e.g. v0.1]
v0.4 aka d8b4fe3

**Additional context**
Nothing else

**Comment by SuperSaiyajinVoltZ** [comment] 2019-06-30 09:59
It works fine on a 3DS with TWiLightMenu. I test it on a DSi in a bit.

**Comment by SuperSaiyajinVoltZ** [comment] 2019-06-30 10:08
It works fine on my DSi as well.. I can't reproduce the Issue. Are you sure you use the latest TWiLightMenu Version as well? v8.5.1.

**Comment by Zayne64** [comment] 2019-06-30 14:00
@SuperSaiyajinVoltZ I'm not using the latest twilightmenu.

**Comment by antoine62** [comment] 2019-06-30 14:02
Update it i think?

**Comment by SuperSaiyajinVoltZ** [comment] 2019-06-30 14:02
Try the latest Version one and tell us, if it happens again.

**Comment by Zayne64** [comment] 2019-07-01 15:03
@SuperSaiyajinVoltZ Sorry but i'd prefer to stay on the older version.

**Comment by FlameKat53** [comment] 2019-07-01 15:07
Why?

**Comment by SuperSaiyajinVoltZ** [comment] 2019-07-01 15:15
tbh, there is no Point to not update to the latest Version, because this may fix Bugs. [Probably also for pkmn-chest]

**Comment by Epicpkmn11** [comment] 2019-07-01 18:56
This is currently a bug, however it should only affected the bank.
I've got it fixed on my MacBook already, I just haven't committed it yet.

**Comment by Epicpkmn11** [comment] 2019-07-02 01:54
Fixed in e857a63

**Closed by Epicpkmn11** 2019-07-02 01:54 UTC
Labels: bug
